### ISSUE TITLE
URL has changed

### ISSUE THREAD

**Issue by woook** [moka-guys/PanelApp_API#8]
See https://panelapp.genomicsengland.co.uk/#!Webservices

**Comment by aledj2** [comment]
I assume that's not the only thing that has changed!


Aled

Aled Jones
Clinical Bioinformatician
Genetics Laboratories| 5th Floor Tower Wing | Guy's Hospital | Great Maze Pond | London | SE1 9RT
Tel: 02071881701
Email: aledjones@nhs.net
________________________________

**Comment by aledj2** [comment]
done in c53b8bef1b5bdf1d113a1d64cb2041420c62ce6a
